### ISSUE TITLE
First steps with rousette

### ISSUE THREAD

**Issue by capiman** [CESNET/rousette#10]
I was meanwhile able to compile rousette.
I have changed "::1" to a local IPv4 address (but later perhaps does not matter, just for info).
I also got spdlog not running, due to problem with systemd not correct/not available, but switched to console output of spdlog.
(I will have a look later)

When I start rousette, I get

```
# rousette
[2024-08-07 13:39:36.952] [info] NACM config validation: Anonymous user access disabled
[2024-08-07 13:39:36.954] [warning] Telemetry disabled. No CzechLight YANG modules found.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Module ietf-restconf@2017-01-26 is not implemented in sysrepo
Aborted (core dumped)
#
```

So I have done this:

```
wget https://raw.githubusercontent.com/YangModels/yang/main/standard/ietf/RFC/ietf-restconf%402017-01-26.yang

sysrepoctl -i ietf-restconf@2017-01-26.yang
```

Now I can start rousette

```
# rousette
[2024-08-09 05:53:07.739] [console] [debug] NACM config validation: no rule-list entries
[2024-08-09 05:53:07.739] [console] [info] NACM config validation: Anonymous user access disabled
[2024-08-09 05:53:07.740] [console] [warning] Telemetry disabled. No CzechLight YANG modules found.
[2024-08-09 05:53:07.743] [console] [debug] Listening at 10.6.128.27 10080
I am in main of rousette Pos 1
```

Every request like

```
curl -v -i -X GET https://10.6.128.27:10080/.well-known/host-meta --header "Accept: application/xrd+xml" -u user=admin
```

or 

```
curl -v -i -X GET http://10.6.128.27:10080/restconf/ietf-system:system --header "Accept: application/yang-data+json;q=0.4,application/yang-data+xml"
```

is not anwering and curl is telling me:

```
# curl -v -i -X GET
http://10.6.128.27:10080/.well-known/host-meta
--header "Accept: application/xrd+xml"
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 10.6.128.27:10080...
* Connected to 10.6.128.27 (10.6.128.27) port 10080
> GET /.well-known/host-meta HTTP/1.1
> Host: 10.6.128.27:10080
> User-Agent: curl/8.8.0
> Accept: application/xrd+xml
>
* Request completely sent off
* Empty reply from server
* Closing connection
curl: (52) Empty reply from server
#
```

Do I perhaps miss to setup NACM? Would it react in this way? Do you have an example NACM file, which I can use for first steps?

If it must be something else, where would be a good point to try debugging?

**Comment by capiman** [comment]
Could HTTP/1.1 <-> HTTP2 be a problem?

But reaction is the same:

```
$ curl -v --http2 -i -X GET
http://192.168.177.27:10080/.well-known/host-meta
--header "Accept: application/xrd+xml"
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 192.168.177.27:10080...
* Connected to 192.168.177.27 (192.168.177.27) port 10080 (#0)
> GET /.well-known/host-meta HTTP/1.1
> Host: 192.168.177.27:10080
> User-Agent: curl/7.88.1
> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c
> HTTP2-Settings: AAMAAABkAAQCAAAAAAIAAAAA
> Accept: application/xrd+xml
>
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server
$
```

**Comment by capiman** [comment]
The problem seems to be independant of rousette. Same problem happens with server example of nghttp2-asio.

**Comment by jktjkt** [comment]
Sorry for a late reply. `rousette` is designed to run behind a reverse proxy because it only implements the "raw" bits of the HTTP/2 protocol, with no TLS and no HTTP/1.1 upgrades. If you want to use `curl` to talk to `rousette` directly, you have to use the `--http2-prior-knowledge` flag instead of `--http2`.

For production deployments, we use something like:
```
nghttpx --accesslog-syslog -f '*,80;no-tls' -b '::1,81;;proto=h2' -b '::1,10080;/telemetry/:/restconf/;proto=h2' --add-forwarded=for
```
...which gives you both HTTP/1.1 and HTTP/2 server.

We also have quite a lot of patches in the queue which improve the docs (and add a ton of features), but they're still pending on some internal libyang/libnetconf2 upgrade complications; take a look at your Gerrit patches if you're interested in the recent developments (or wait a bit till we solve that).
