### ISSUE TITLE
Put request processing should probably lock the datastore

### ISSUE THREAD

**Issue by peckato1** [CESNET/rousette#2]
In the PUT request writes we first check if the node we want to insert is present. This is needed for deducing the correct HTTP status code.

> Consistent with [[RFC7231](https://www.rfc-editor.org/rfc/rfc7231)], if the PUT request creates a new resource,
>   a "201 Created" status-line is returned.  If an existing resource is
>   modified, a "204 No Content" status-line is returned.

These are 2 operations into the DS (first query for existence, then the actual write) while the DS is not locked. This means that somebody could change the the DS *after* we query but *before* we actually write into the datastore (i.e., he/she can insert/erase the data node we want to insert) and the status code would be invalid.

**Comment by jktjkt** [comment]
(and it's likely not just `PUT`, it's any method which validates whether something exists, and then goas ahead and does something.)
