### ISSUE TITLE
Current status of rousette

### ISSUE THREAD

**Issue by mattiaswal** [CESNET/rousette#8]
What is the current status of rousette?
What is missing for the first release?

**Comment by peckato1** [comment]
Hi, the latest "devel" patch can be found here: https://gerrit.cesnet.cz/c/CzechLight/rousette/+/7230/2 You can checkout it using the Download button.

Currently we are working on notification streams, they should hopefully land soon(TM).

**Comment by jktjkt** [comment]
FYI, that rather large queue of pending changes has just been merged.
